### PR TITLE
Fixed dependencies

### PR DESCRIPTION
**Pull request by sheetalkadwal**
**Trello Card:** https://trello.com/c/SDGzEcWq/1-review-and-fix-media-shuttle-api-nodejs-client

**Commit Summary**
**d4cf355**: Fixed dependencies for the sample code
**ea9c47f**: Removed deprecated warning of querystring and used URLSearchParams API instead.

### CODE REVIEW

**Comment by sheetalkadwal** [comment]
Hi Tobo, The only warning that we are getting now after fixes is: 

`deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.`

URLSearchParams is recommended for new codes (may need more changes) and the old query string is also being maintained and good from performance perspective, so I haven't changed that.

**Comment by tobsign** [comment]
> Hi Tobo, The only warning that we are getting now after fixes is:
> 
> `deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.`
> 
> URLSearchParams is recommended for new codes (may need more changes) and the old query string is also being maintained and good from performance perspective, so I haven't changed that.

@sheetalkadwal were you able to scope the code changes that will be needed to replace querystring? In which parts of the code is querystring used? I'll rather remove that dependency if possible and use URLSearchParams if not significant effort. Thanks

**Comment by sheetalkadwal** [comment]
> > Hi Tobo, The only warning that we are getting now after fixes is:
> > `deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.`
> > URLSearchParams is recommended for new codes (may need more changes) and the old query string is also being maintained and good from performance perspective, so I haven't changed that.
> 
> @sheetalkadwal were you able to scope the code changes that will be needed to replace querystring? In which parts of the code is querystring used? I'll rather remove that dependency if possible and use URLSearchParams if not significant effort. Thanks

Sure, looking into this.

**Comment by sheetalkadwal** [comment]
Hi @tobsign, Removed the deprecated warning of the query string and used URLSearchParams API instead.

**Review by tobsign — APPROVED** [review]
lgtm.

**Pull request merged**
